# Generated by Django 5.0.2 on 2024-02-26 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes_Gen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='given_by',
        ),
    ]
