# Generated by Django 5.0.2 on 2024-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotes_Gen', '0002_remove_quotes_given_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quotes', models.TextField()),
                ('given_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Quotes',
        ),
    ]
